apiVersion: v1
kind: Service
metadata:
  name: sneaker-app
spec:
  selector:
    app: hello
    tier: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "34.176.173.38"